### ISSUE TITLE
False new paired device

### ISSUE THREAD

**Issue by max5962** [elric91/homeassistant_zigate#6]
Hello.
Sometimes, we received “Breaking news new device xxxx found" and the device is already in conf.
Thanks.

**Comment by ISO-B** [comment]
Is this random thing? What type.of device does this? I have noticed that lights announce their address when powered on.

**Comment by elric91** [comment]
It happened to me with door sensor as well. I plan to check if the device exists in the conf before sending the message (need to understand how to do it in HA)

**Comment by max5962** [comment]
@ISO-B Completely random... 
It happened to me with : 
temp sensors
door sensors

thantks but  it's really not urgent :)

**Comment by alexbarcelo** [comment]
I own several (10) Aqara wall switches, and those messages flood my frontpage. I counted 1000 messages overnight.

I suppose that either checking if he device exists *or* only show the persistent notification if that has been triggered due to a pairing state (haven't checked zigate packets, don't know if that is even possible).

**Comment by ISO-B** [comment]
This should be now fixed.

**Comment by alexbarcelo** [comment]
After waiting a couple of hours, it seems to be fixed.

Great! Thanks :)
